//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BspInfo
{
	const	int MAX_MAP_HULLS = 4;
	const	int MAX_MAP_MODELS = 400;
	const	int MAX_MAP_BRUSHES = 4096;
	const	int MAX_MAP_ENTITIES = 1024;
	const	int MAX_MAP_ENTSTRING = (128 * 1024);
	const	int MAX_MAP_PLANES = 32767;
	const	int MAX_MAP_NODES = 32767;
	const	int MAX_MAP_CLIPNODES = 32767;
	const	int MAX_MAP_LEAFS = 8192;
	const	int MAX_MAP_VERTS = 65535;
	const	int MAX_MAP_FACES = 65535;
	const	int MAX_MAP_MARKSURFACES = 65535;
	const	int MAX_MAP_TEXINFO = 8192;
	const	int MAX_MAP_EDGES = 256000;
	const	int MAX_MAP_SURFEDGES = 512000;
	const	int MAX_MAP_TEXTURES = 512;
	const	int MAX_MAP_MIPTEX = 2097152;
	const	int MAX_MAP_LIGHTING = 2097152;
	const	int MAX_MAP_VISIBILITY = 2097152;
	const	int MAX_MAP_PORTALS = 65536;
 
public	int mapNum_hulls;
	public	int mapNum_models;
	public	int mapNum_brushes;
	public	int mapNum_entities;
	public	int mapNum_entstring;
	public	int mapNum_planes;
	public	int mapNum_nodes;
	public	int mapNum_clipnodes;
	public	int mapNum_leafs;
	public	int mapNum_verts;
	public	int mapNum_faces;
	public	int mapNum_marksurfaces;
	public int mapNum_texinfo;
	public	int mapNum_edges;
	public	int mapNum_surfedges;
	public	int mapNum_textures;
	public	int mapNum_miptex; 
	public	int mapNum_lighting;
	public	int mapNum_visability;
	public	int mapNum_portals;


		public  BspInfo ()
		{
	
		}

}

